# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ApiManagement' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for ApiManagement

  target 'ApiManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ApiManagementUITests' do
    # Pods for testing
  end

end
